server:
  port: 8090

ymltest:
  str_test1: q \n z \t j${ymltest.default:default}

  str_test2: "q \n z \t j"

  str_test3: 'q \n z \t j'

  date: 2019/8/19

  device:
    id: Dev001
    name: 设备001

  user_map: {0: 超级管理员, 1: 管理员}

  brw_list:
    - Dev001
    - 2019-8-19 19:38:23
    - 0